export const INITIALIZING_CODES = 'INITIALIZING_CODES';
export const FETCHING_CODES = 'FETCHING_CODES';
export const STORING_CODES = 'STORING_CODES';
export const STORE_CODES_SUCCESS = 'STORE_CODES_SUCCESS';
export const STORE_CODES_FAILED = 'STORE_CODES_FAILED';
export const FETCH_CODES_SUCCESS = 'FETCH_CODES_SUCCESS';
export const FETCH_CODES_FAILED = 'FETCH_CODES_FAILED';

